import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { RulesEngine } from '../web/rules-engine.js';

const rules = JSON.parse(readFileSync(new URL('../web/data/rules.json', import.meta.url), 'utf8'));
const workbook = JSON.parse(readFileSync(new URL('../web/data/workbook.json', import.meta.url), 'utf8'));
const named = (rows, name) => {
  const found = rows.filter((row) => row.name === name);
  assert.equal(found.length, 1, '唯一规则条目：' + name);
  return found[0];
};

// Independent expected examples are transcribed from the local rulebook pages,
// not generated by the extraction script or from the emitted JSON.
const expectedArchetypes = [
  ['学者', 4, 6, '逻辑', '学习', 30],
  ['医生', 4, 6, '逻辑', '医学', 31],
  ['猎人', 2, 4, '精准', '远程战斗', 32],
  ['神秘学家', 1, 4, '精准', '隐秘行动', 33],
  ['军官', 3, 7, '精准', '远程战斗', 34],
  ['牧师', 4, 6, '共情', '观察', 35],
  ['私家侦探', 2, 5, '逻辑', '调查', 36],
  ['仆人', 2, 4, '体能', '力量', 37],
  ['流浪者', 1, 3, '体能', '操控人心', 38],
  ['作家', 2, 5, '共情', '启迪', 39],
];

test('ten base archetypes match the independent book pages, including priest cap 6 and servant Strength', () => {
  assert.equal(rules.archetypes.length, 11);
  assert.equal(rules.archetypes.filter((row) => row.verified).length, 10);
  for (const [name, minimum, maximum, attribute, skill, page] of expectedArchetypes) {
    const actual = named(rules.archetypes, name);
    assert.deepEqual([actual.resourceMin, actual.resourceMax, actual.mainAttribute, actual.mainSkill, actual.source.pdfPage], [minimum, maximum, attribute, skill, page], name);
    assert.equal(actual.talents.length, 3);
    assert.equal(actual.verified, true);
    for (const talent of actual.talents) assert.equal(named(rules.talents, talent).category, name);
    assert.equal(actual.equipmentChoices.length, 3);
  }
  const hunter = named(rules.archetypes, '吸血鬼猎人');
  assert.deepEqual([hunter.resourceMin, hunter.resourceMax, hunter.mainAttribute, hunter.mainSkill], [1, 3, '精准', '近身战斗']);
  assert.equal(hunter.verified, false);
  assert.equal(hunter.source.pdfPage, null);
});

test('rulebook starting equipment retains real choices and corrects mistranscribed liquor and tools', () => {
  assert.deepEqual(named(rules.archetypes, '学者').equipmentChoices, [['藏书', '地图集'], ['书写工具'], ['烈酒', '计算尺']]);
  assert.deepEqual(named(rules.archetypes, '流浪者').equipmentChoices, [['拐杖'], ['小刀', '撬棍'], ['宠物犬', '烈酒']]);
  assert.deepEqual(named(rules.archetypes, '私家侦探').equipmentChoices, [['放大镜', '开锁器'], ['左轮手枪'], ['指虎', '双筒望远镜']]);
  assert.match(named(rules.archetypes, '神秘学家').equipment, /火绒盒/);
  assert.match(named(rules.archetypes, '军官').equipment, /地图册/);
  assert.match(named(rules.archetypes, '作家').equipment, /观剧镜/);
});

test('54 book talents and 3 explicitly unverified expansion talents have complete descriptions and sensible activation', () => {
  assert.equal(rules.talents.length, 57);
  assert.equal(new Set(rules.talents.map((talent) => talent.name)).size, 57);
  assert.equal(rules.talents.filter((talent) => talent.verified).length, 54);
  assert.equal(rules.talents.filter((talent) => talent.category === '通用').length, 24);
  assert.deepEqual(rules.talents.filter((talent) => !talent.verified).map((talent) => talent.name).sort(), ['吸血者恨意', '猎杀时刻', '穿刺者'].sort());
  const wealthy = named(rules.talents, '富有');
  assert.equal(wealthy.repeatable, true);
  assert.deepEqual(wealthy.effects.map(({ type, amount, activation }) => [type, amount, activation]), [['resourceBonus', 1, 'always']]);
  assert.equal(named(rules.talents, '勇敢').effects[0].target, '恐惧');
  assert.equal(named(rules.talents, '勇敢').effects[0].amount, 1);
  assert.equal(named(rules.talents, '拳击手').effects[0].target, 'unarmed');
  assert.equal(named(rules.talents, '拳击手').effects[0].type, 'damageBonus');
  assert.equal(named(rules.talents, '书虫').effects[0].activation, 'manual');
  assert.equal(named(rules.talents, '神射手').effects[0].activation, 'manual');
  assert.match(named(rules.talents, '联络人').description, /GM.*谜题不再有趣/);
  assert.equal(rules.talentAliases['人多胆壮'], '人多壮胆');
});

test('seven skill immunities and action-limited bonuses preserve the source conditions and unresolved medicine note', () => {
  for (const [name, skill] of [
    ['知识是可靠的', '学习'], ['应急医学', '医学'], ['绅士', '操控人心'],
    ['专注', '调查'], ['疑心', '警觉'], ['墨客', '启迪'], ['同理心', '观察'],
  ]) {
    const modifier = named(rules.talents, name).effects[0];
    assert.equal(modifier.type, 'ignoreConditions', name);
    assert.equal(modifier.target, skill, name);
  }
  assert.match(named(rules.talents, '应急医学').effects[0].ambiguity, /官方没有勘误/);
  assert.match(named(rules.talents, '双手武器专精').effects[0].condition, /双武器/);
  assert.equal(named(rules.talents, '坚韧').effects[0].uses.count, 1);
  assert.equal(named(rules.talents, '坚韧').effects[0].uses.period, 'session');
  assert.equal(named(rules.talents, '献身').effects[0].conditionType, 'mental');
  assert.equal(named(rules.talents, '主任医师').effects[0].amount, 4);
  assert.equal(named(rules.talents, '主任医师').effects[0].replaces, 3);
});

test('all eight economic bands match PDF 77 trade modifiers and standard assets', () => {
  assert.deepEqual(rules.resources.map(({ value, name, exchangeBonus, assets }) => [value, name, exchangeBonus, assets]), [
    [1, '赤贫', -1, 0], [2, '贫穷', 0, 0], [3, '挣扎', 0, 1], [4, '经济稳定', 1, 2],
    [5, '中产', 1, 3], [6, '小康', 2, 5], [7, '富有', 3, 8], [8, '大富豪', 5, 12],
  ]);
  for (const band of rules.resources) {
    assert.ok(band.description.startsWith(band.name + '。'));
    assert.equal(band.source.pdfPage, 26);
    assert.equal(band.adjustmentSource.pdfPage, 77);
  }
  assert.equal(rules.resources[0].assetsText, '-');
  assert.equal(rules.resources[1].exchangeBonusText, '-');
});

test('three armor rows, ranged boundaries and dual-skill spear match independent weapon table examples', () => {
  assert.deepEqual(rules.armor.map(({ name, protection, agility, availability }) => [name, protection, agility, availability]), [
    ['轻甲', 2, -1, 2], ['中甲', 4, -2, 3], ['重甲', 6, -3, 4],
  ]);
  assert.equal(rules.weapons.length, 23);
  for (const [name, damage, range, bonus, availability, skills] of [
    ['拳击或踢击', 1, '0', 0, null, ['力量']],
    ['剑或军刀', 2, '0', 2, 4, ['近身战斗']],
    ['戟', 3, '0', 1, 4, ['近身战斗']],
    ['矛', 1, '0-1', 1, 1, ['近身战斗', '远程战斗']],
    ['十字弓', 2, '0-1', 1, 3, ['远程战斗']],
    ['手枪或左轮', 2, '0-1', 2, 4, ['远程战斗']],
    ['来复枪', 2, '1-3', 2, 4, ['远程战斗']],
    ['加农炮', 5, '2-5', 1, 5, ['远程战斗']],
  ]) {
    const actual = named(rules.weapons, name);
    assert.deepEqual([actual.damage, actual.range, actual.bonus, actual.availability, actual.skills], [damage, range, bonus, availability, skills], name);
  }
  assert.equal(named(rules.weapons, '来复枪').rangeMin, 1);
  assert.match(named(rules.weapons, '来复枪').warnings.join(''), /不能攻击同一区域/);
  assert.equal(named(rules.weapons, '拳击或踢击').kind, 'unarmed');
});

test('42 equipment records preserve conditional bonuses instead of adding them permanently', () => {
  assert.equal(rules.equipment.length, 42);
  for (const [name, bonus, availability, skills] of [
    ['开锁器', 1, 2, ['隐秘行动']],
    ['双筒望远镜', 2, 2, ['警觉']],
    ['医疗设备', 2, 2, ['医学']],
    ['猎犬', 3, 3, ['近身战斗', '调查', '警觉']],
    ['绳梯', 3, 2, ['敏捷', '力量']],
    ['强效毒药（剂量2）', 0, 2, []],
  ]) {
    const actual = named(rules.equipment, name);
    assert.equal(actual.bonus, bonus, name);
    assert.equal(actual.availability, availability, name);
    assert.deepEqual([...actual.skills].sort(), [...skills].sort(), name);
    assert.equal(actual.activation, 'manual', name);
  }
  assert.match(named(rules.equipment, '强效毒药（剂量2）').effect, /毒性6/);
});

test('food and disguise semantics do not grant bonuses to waived or replaced checks', () => {
  // PDF 79 says food removes the need for Strength checks, and fine disguises
  // allow Manipulation to replace Stealth. The original table bonus is retained.
  for (const name of ['粗制干粮', '营养食品']) {
    const food = named(rules.equipment, name);
    assert.equal(food.bonus, 1);
    assert.deepEqual(food.skills, []);
    assert.match(food.effect, /不需要力量检定/);
    const engine = new RulesEngine(workbook, rules, {
      '角色卡!D20': 3, '角色卡!D23': 1, '角色卡!A30': name,
    });
    assert.equal(engine.roll({ kind: 'skill', skill: '力量', equipmentRows: [30] }).pool, 4);
  }
  const disguise = named(rules.equipment, '高档伪装物');
  assert.equal(disguise.bonus, 2);
  assert.deepEqual(disguise.skills, ['操控人心']);
  assert.match(disguise.effect, /操控人心检定替代隐秘行动/);
  const engine = new RulesEngine(workbook, rules, {
    '角色卡!I20': 4, '角色卡!I23': 3, '角色卡!S20': 2,
    '角色卡!S22': 1, '角色卡!A30': '高档伪装物',
  });
  assert.equal(engine.roll({ kind: 'skill', skill: '隐秘行动', equipmentRows: [30] }).pool, 7);
  assert.equal(engine.roll({ kind: 'skill', skill: '操控人心', equipmentRows: [30] }).pool, 5);
});

test('creation and growth budgets, XP and dice minimum come from distinct rulebook statements', () => {
  assert.deepEqual(rules.ageGroups.map(({ min, max, attributePoints, skillPoints }) => [min, max, attributePoints, skillPoints]), [[17, 25, 15, 10], [26, 50, 14, 12], [51, null, 13, 14]]);
  assert.equal(rules.rules.creation.primaryAttributeMax, 5);
  assert.equal(rules.rules.creation.attributeMax, 4);
  assert.equal(rules.rules.creation.skillMax, 2);
  assert.equal(rules.rules.creation.primarySkillMax, 3);
  assert.equal(rules.rules.growth.xpCost, 5);
  assert.equal(rules.rules.growth.skillMax, 5);
  assert.equal(rules.rules.growth.canImproveAttributes, false);
  assert.equal(rules.rules.dice.minimum, 1);
  assert.equal(rules.rules.fear.maxCompanionBonus, 3);
  assert.equal(rules.rules.advantage.bonus, 2);
  assert.equal(rules.rules.xpQuestions.questions.length, 8);
  assert.match(rules.rules.xpQuestions.questions[7], /非凡/);
});

test('every book source resolves to an actual Markdown section and PDF page anchor, while expansion sources cite real workbook cells', () => {
  const cache = new Map();
  function verifySource(reference, label) {
    assert.ok(reference && typeof reference === 'object', label);
    if (reference.pdfPage === null) {
      assert.match(reference.label, /基础规则书未核验/, label);
      const sheet = workbook.sheets.find((item) => item.name === reference.sheet);
      assert.ok(sheet, label);
      const firstCell = reference.range.split(':')[0];
      assert.ok(Object.hasOwn(sheet.cells, firstCell), label);
      return;
    }
    assert.equal(reference.document, '北欧奇谭规则书.pdf', label);
    assert.ok(Number.isInteger(reference.pdfPage) && reference.pdfPage >= 1 && reference.pdfPage <= 240, label);
    assert.equal(reference.printedPage, reference.pdfPage - 4, label);
    if (!cache.has(reference.markdown)) cache.set(reference.markdown, readFileSync(new URL('../' + reference.markdown, import.meta.url), 'utf8'));
    const markdown = cache.get(reference.markdown);
    assert.ok(markdown.includes('<a id="pdf-page-' + reference.pdfPage + '"></a>'), label + ' PDF anchor');
    assert.ok(markdown.includes('<a id="' + reference.anchor + '"></a>'), label + ' section anchor');
  }
  for (const collection of ['archetypes', 'talents', 'resources', 'armor', 'weapons', 'equipment', 'cover', 'services', 'ageGroups', 'skills', 'warnings']) {
    for (const item of rules[collection]) {
      verifySource(item.source, collection + ':' + (item.name ?? item.code ?? item.value));
      if (item.adjustmentSource) verifySource(item.adjustmentSource, collection + ':adjustment');
    }
  }
  for (const [name, entry] of Object.entries(rules.rules)) {
    verifySource(entry.source, 'rules:' + name);
    if (entry.skillSource) verifySource(entry.skillSource, 'rules:' + name + ':skills');
  }
  const pdf = readFileSync(new URL('../' + rules.source.path, import.meta.url));
  assert.equal(createHash('sha256').update(pdf).digest('hex'), rules.source.sha256);
});
